"""
One-time script to rebuild the FAISS index using fastembed (ONNX-backed).
Run this locally, then commit the regenerated vectorstore/index.faiss
(metadata.json stays unchanged since it already has the text).

IMPORTANT: This must be run with fastembed installed, using the SAME
library the app queries with at runtime (rag/embeddings.py). Vectors
generated by sentence-transformers vs fastembed for "the same" model
can differ slightly, so mixing libraries between index-build and
query-time will silently degrade retrieval quality.
"""

import json
import faiss
import numpy as np
from fastembed import TextEmbedding

METADATA_PATH = "vectorstore/metadata.json"
OUTPUT_INDEX_PATH = "vectorstore/index.faiss"

# Must match whatever you set config.EMBEDDING_MODEL to
NEW_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

def main():
    print(f"Loading metadata from {METADATA_PATH}...")
    with open(METADATA_PATH, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    print(f"Loaded {len(metadata)} chunks.")

    print(f"Loading embedding model: {NEW_MODEL_NAME}")
    model = TextEmbedding(model_name=NEW_MODEL_NAME)

    texts = [chunk["text"] for chunk in metadata]

    print("Generating embeddings for all chunks...")
    embeddings = np.array(list(model.embed(texts)), dtype="float32")

    # fastembed's MiniLM output is already normalized, but normalize
    # explicitly to guarantee cosine-equivalence with IndexFlatIP
    faiss.normalize_L2(embeddings)

    dimension = embeddings.shape[1]
    print(f"Embedding dimension: {dimension}")

    print("Building FAISS index...")
    index = faiss.IndexFlatIP(dimension)  # inner product (cosine, since normalized)
    index.add(embeddings)

    print(f"Index now has {index.ntotal} vectors.")

    faiss.write_index(index, OUTPUT_INDEX_PATH)
    print(f"Saved new index to {OUTPUT_INDEX_PATH}")

if __name__ == "__main__":
    main()